### PR TITLE
Handle multi-column unique indices properly

### LINKED ISSUE #9: Multicolumn unique indexes are not handled correctly
If a unique index contains multiple columns, then all the columns are marked as being independently unique. This leads to incorrect code generation when one of the columns is a foreign key, as it implies a one-to-one relationship.

```SQL
create table example (
    id                  integer  not null primary key,
    other_id            integer  not null references other(id),
    type                text     not null,

    constraint other_type_unique unique (other_id, type)
);
```

Leads to code that looks like this:

```go
type otherR struct {
	Example *Example
}
```

in `other.go` instead of:

```go
type otherR struct {
	Examples ExampleSlice
}
```

### PR DESCRIPTION
**Pull request by James-REANNZ**
A column is not itself unique if the index enforcing the constraint has
multiple columns, not handling this results in incorrect code generation
when a foreign key column is contained in a multi-column unique
constraint. Specifically, the "foreign" side of the relationship would be
generated as a "one-to-one" relationship, rather than a "one-to-many"
relationship.

Fixes #9.

### CODE REVIEW

**Comment by aarondl** [comment]
I'm trying to think if this breaks anything... Having a fkey on a single column, but a unique index across that fkey AND another column indeed does not make the fkey column itself unique.

It seems like a fine change. Though as per CONTRIBUTING.md this is targeted at the wrong branch.

**Comment by James-REANNZ** [comment]
Doesn't look like I can change the branch the PR is targeting, so I'll open a new one.

**Comment by James-REANNZ** [comment]
There does not appear to be a `dev` branch in this repo, I can re-open this PR, or wait for somebody to create a `dev` branch.

**Comment by James-REANNZ** [comment]
Re-opening since there's not been any response to my question.

**Comment by aarondl** [comment]
Thanks for the PR, sorry forgot this wasn't on the main repo :p

**Pull request merged**
